SKILLS_DB = [
    "python",
    "java",
    "c++",
    "sql",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pytorch",
    "pandas",
    "numpy",
    "scikit-learn",
    "nlp",
    "data analysis",
    "data science",
    "docker",
    "kubernetes",
    "git",
    "github",
    "tableau",
    "power bi",
    "excel",
    "statistics",
    "fastapi",
    "flask",
    "streamlit"
]